first version of filters search with pagination
ledavto/Team-JS pull request #6
Opened 2023-10-21 15:53 UTC by Kalugaa

Наче все зроблено, але якщо щось знайдеш не те, буду дуже вдячний, бо вже нічого не бачу)

2023-10-21 16:58 UTC, Br0kEnM1Nd-Git requested changes

2023-10-21 16:58 UTC, Br0kEnM1Nd-Git commented on src/partials/exercises.html
> +    <button id="bodypart-filter">Body Part</button>
id краще замінити на data-id атрибут

2023-10-21 17:28 UTC, Kalugaa commented on src/js/exercises.js
> +let itemsPerPage;
Якщо комусь вони потрібні то без питань)

2023-10-21 17:29 UTC, Kalugaa commented on src/js/exercises.js
> +    .getExFilters({ filter: subcategory, page, limit: itemsPerPage })
Завтра зміню 🫡

2023-10-21 17:31 UTC, Kalugaa commented on src/partials/exercises.html
> +    <button id="bodypart-filter">Body Part</button>
То я ж тут просто звертаюсь за айдішкою до кнопок, ці кнопки тільки для того щоб перевірити функціонал і щоб Марина могла ці айдішки додати на свої кнопки

2023-10-22 07:42 UTC, ledavto approved these changes

2023-10-22 08:18 UTC, merged